spring:
  activemq:
   #ActiveMQ通讯地址
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    # 在考虑结束之前等待的时间
    close-timeout: 15s
     # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    in-memory: false
    # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    non-blocking-redelivery: false
    # 等待消息发送响应的时间。设置为0等待永远。
    send-timeout: 0
    
    queue-name: active.queue
    topic-name: active.topic
    pool:
    #是否替换默认的连接池，使用ActiveMQ的连接池需引入的依赖
      enabled: true
      #连接池最大连接数
      max-connections: 10
      #空闲的连接过期时间，默认为30秒
      idle-timeout: 30000
      #使用queue模式的时候，需要把application.properties文件中的spring.jms.pub-sub-domain=true 注释掉。
#如果是点对点（queue），那么此处默认应该是false，如果发布订阅，那么一定设置为true
#  jms:
#    pub-sub-domain: true
    